# Site settings
title:         一周一译
description:    一周翻译一篇英语文章，对过去岁月最好的纪念

# Author
author:
  name:         Tiger
  url:          http://zhanghongjiang.me
  email:        mytiger@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
